version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: my-rabbit
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
  sequencewebapi:
    image: ${DOCKER_REGISTRY-}sequencewebapi
    build:
      context: .
      dockerfile: SequenceWebApi/Dockerfile
    ports:
      - "5000:443"
